# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.3'
services:
  evaluar_cursos_jh-app:
    image: evaluar_cursos_jh
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=dev,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-jh:3306/db-jh?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_LIQUIBASE_URL=jdbc:mysql://db-jh:3306/db-jh?useSSL=false&allowPublicKeyRetrieval=true
      - JHIPSTER_SLEEP=5 # gives time for other services to boot before the application
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:8080:8080
  db-jh:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=db
      # So you don't have to use root, but you can if you like
      - MYSQL_USER=root
      # You can use whatever password you like
      - MYSQL_PASSWORD=1234
      # Password for root access
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - 3305:3306
    expose:
      # Opens port 3306 on the container
      - 3306
      # Where our data will be persisted
    volumes:
      - my-db2:/var/lib/mysql

volumes:
  my-db2:
    external: true
